---
- hosts: 167.172.232.200
  tasks:
    - name: Install packages
      apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - apache2
          - tree
          - git

    - name: Ensure Apache is running and enabled
      service:
        name: apache2
        state: started
        enabled: true

    - name: Create groups
      group:
        name: "{{ item }}"
      loop:
        - kaizen
        - devops
        - qa

    - name: Create user ruslan and add to groups
      user:
        name: ruslan
        groups: kaizen,qa
        append: yes

    - name: Create user tester and add to group
      user:
        name: tester
        groups: qa
        append: yes

    - name: Copy Homework1 folder to remote user's home
      synchronize:
        src: "{{ playbook_dir }}"
        dest: "/root/"
        recursive: yes
